title: Andrew Glyadchenko
author: GitHub User
email: andrewgly95@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of some of the projects I've built over the years

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
